name: forum
mode: dev
port: 8080
start_time: 2023-08-07
machine_id: yyt
log:
  level: debug
  filename: ./log/forum.log
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: yUYANTAO
  dbname: forum

redis:
  host: 127.0.0.1
  user: root
  password: ''
  port: 6379
  db: 0
