1000="The system is abnormal, contact the administrator"
1001="Please login first"


2000="The business is abnormal, contact the administrator"
2001="Request parameter exception"
2002="The user already exists"
2003="The user does not exist"
2004="The password is incorrect"
2005="User not logged in"
2006="Data does not exist"
2007="Voting time is over"